### PR TITLE
First pass adding SP HTML Asset

### PR DESCRIPTION
**Pull request by rhyolight**
Luiz, please have a look at the `<Code>` blocks I put into the SP details React page. I have 3 code blocks, and 2 problems. 

The first problem is that each Code block seems to be an inline component instead of a block component (Code should be able to span several lines):

> screen shot 2018-01-29 at 1 02 02 pm

The 2nd problem is that the 3rd code block fails lint/parse for an unknown reason:

```
WARNING in ./pages/spatial-pooling-algorithm-details/index.jsx
Module build failed: SyntaxError: Unexpected token (376:53)

  374 |                     activeDutyCycleNeighbors)
  375 |                 overlapDutyCycle(c) = updateOverlapDutyCycle(c)
> 376 |                 if overlapDutyCycle(c) < minDutyCycle(c) then
      |                                                      ^
  377 |                     increasePermanences(c, 0.1*connectedPerm)
  378 |             inhibitionRadius = averageReceptiveFieldSize()
  379 |           </Code>
```

This looks like the code within the block is being parsed for some reason, but it should not be... Do you have any insight into either of these issues?

### CODE REVIEW

**Comment by rhyolight** [comment]
@lscheinkman To replicate 2nd error, simply run `npm run lint`.

**Comment by lscheinkman** [comment]
@rhyolight Why not pure markdown for the index page?

**Comment by rhyolight** [comment]
I dunno just trying to match the work that was already in place. 

By the way, adding a `<pre>` around the `<Code>` block does not help because the string contents of the block seem to have newlines stripped from them. The markup ends up looking like this:

```html
<pre>
  <code class="index_code_1n2tk tachyons_bg-light-gray_2vMTS tachyons_db_32y4n tachyons_f6_14UFF tachyons_lh-copy_15fP- tachyons_mb3_1mVjM tachyons_nowrap_3x4vg tachyons_overflow-auto_1h0We tachyons_ph3_QxldC tachyons_pv2_1UD2U">
    for c in columns overlap(c) = 0 for s in connectedSynapses(c) overlap(c) = overlap(c) + input(t, s.sourceInput) overlap(c) = overlap(c) * boost(c)
  </code>
</pre>
```

**Comment by rhyolight** [comment]
Also, I tried creating a `CodeBlock` component that looks like this. I got it working but still had the same problem described above about the newlines. 

```javascript
var CodeBlock = function CodeBlock(_ref) {
  var children = _ref.children;

  var codeBlock = _react2.default.createElement(
    'code',
    { className: _index2.default.code },
    children
  );
  return _react2.default.createElement(
    'pre',
    { className: _index2.default.pre },
    [codeBlock]
  );
};
```

**Comment by lscheinkman** [comment]
@rhyolight How is it different from https://github.com/numenta/numenta-web/tree/master/packages/numenta.com/pages/spatial-pooling-algorithm ?

I would just create a markdown file under the same directory named 'spatial-pooling-algorithm-details.md'

**Comment by rhyolight** [comment]
Markdown won't work for this content because I need tables.

**Comment by lscheinkman** [comment]
Markdown support tables. See https://help.github.com/articles/organizing-information-with-tables/

Here is an example on our web site:
- https://numenta.com/htm-studio/date-time-formats/
- https://numenta.com/papers-videos-and-more/resources/hierarchical-temporal-memory-white-paper/

**Comment by rhyolight** [comment]
I wasn't aware we were using Github markdown (vanilla markdown does not support tables). Either way, it doesn't matter.

**Comment by lscheinkman** [comment]
regarding
> so this needs to exist along with "spatial-pooling-algorithm" and the SP BAMI chapter

We are restructuring the web site for SEO purpose and we need to create content hierarchy. It is better for SEO to add the detail as a child of 'spatial-pooling-algorithm' than at the same level

**Comment by rhyolight** [comment]
I know I did not explain this very well, but this additional web content is just for an A/B test HTML vs PDF access for the SP BAMI chapter. 

All I am doing is creating an HTML version of the SP chapter PDF and hosting it alongside the PDF. Then I will link them both and see which gets more hits over the next few months. I am hoping more people will access the web asset so I can convince the execs to move BAMI from PDF to a web asset.

**Comment by rhyolight** [comment]
Strange, even straight HTML doesn't format properly:

```html          
          <pre>
            <code>
              for c in columns
                  overlap(c) = 0
                      for s in connectedSynapses(c)
                          overlap(c) = overlap(c) + input(t, s.sourceInput)
                      overlap(c) = overlap(c) * boost(c)
            </code>
          </pre>
``` 
turns into

```html
<pre><code>for c in columns overlap(c) = 0 for s in connectedSynapses(c) overlap(c) = overlap(c) + input(t, s.sourceInput) overlap(c) = overlap(c) * boost(c)</code></pre>
```

**Comment by lscheinkman** [comment]
try just <pre>

**Comment by rhyolight** [comment]
No dice. React is taking the string content of the tag and not retaining newlines within the pre tag. I don't really understand why. The same thing is happening with `code`, `pre` and the custom `Code` component.

**Comment by lscheinkman** [comment]
try 
```
<pre>{`
              for c in columns
                  overlap(c) = 0
                      for s in connectedSynapses(c)
                          overlap(c) = overlap(c) + input(t, s.sourceInput)
                      overlap(c) = overlap(c) * boost(c)
          `}</pre>
```

**Comment by rhyolight** [comment]
Yes that worked! Thank you!

**Comment by rhyolight** [comment]
Not ready for merge yet. Still need to add  HTML | PDF links for A/B test. And will talk to Christy Wednesday before merging.

**Comment by lscheinkman** [comment]
@rhyolight The website restructuring was merged (#414). Please make sure your links are in the correct location before merging.

**Comment by rhyolight** [comment]
Ready for review and merge.

**Pull request merged**
