### PR TITLE
[WEB-434] Moves HTM School content from .org to .com

### PR DESCRIPTION
**Pull request by rhyolight**
Move the content over, updated configs of both sites, updated links on .org, updated snapshots. Test passing:

Test Suites: 96 passed, 96 total
Tests:       158 passed, 158 total
Snapshots:   4 updated, 146 passed, 150 total

### CODE REVIEW

**Comment by rhyolight** [comment]
@brev @lscheinkman please review

**Comment by brev** [comment]
@rhyolight You'll want to move the HTM School link from the .org sitemap to the .com sitemap too. Maybe a `school` url var in numenta.com's config.toml?

**Comment by rhyolight** [comment]
Good point. I am also aware that numenta.com/htm-school is not on the numenta.com sitemap or linked anywhere from there. We'll address that with future numenta.com updates to match the .org ones we're going now.

**Comment by rhyolight** [comment]
FYI I did update the numenta.org sitemap to link to `{links.out.school}`, and the numenta.com sitemap does not link to it yet (fine for now).

**Pull request merged**
