### PR TITLE
Update index.jsx

### PR DESCRIPTION
**Pull request by ktyliu**
fix incorrect link to SDR

### CODE REVIEW

**Comment by rhyolight** [comment]
Thanks @ktyliu! This is a very nice change to make. We had not noticed this broken link. In order to contribute, can you please sign our standard contributor's license?

https://numenta.org/licenses/contrib/

**Comment by rhyolight** [comment]
@lscheinkman The CL has been signed! Merge at will.

**Comment by rhyolight** [comment]
This change has been deployed! Thanks again Kevin!

**Comment by ktyliu** [comment]
My pleasure. Thanks for providing the material.
I really like the SDR theory.

2018-05-04 1:58 GMT+10:00 Matthew Taylor <notifications@github.com>:

**Pull request merged**
